'use strict';

/* ===========================================
   Application Data
   =========================================== */

const MODEL_NAMES = {
  densenet: 'DenseNet检测模型',
  ssd: 'SSD检测模型',
  yolov5: 'YOLOv5检测模型',
  yolo: 'YOLOv8检测模型',
  resnet: 'ResNet-18分类模型',
};

const DENSITY_LABELS = {
  high: '高密度',
  medium: '中密度',
  low: '低密度',
  breeding: '繁殖区域',
};

const DENSITY_COLORS = {
  high: '#f44336',
  medium: '#ff9800',
  low: '#ffeb3b',
  breeding: '#9c27b0',
};

const chartConfig = [
  { name: '性能等级分布', description: '展示不同性能等级的模型数量分布情况', src: 'chart_1_performance_level.png' },
  { name: '精度-速度对比', description: '分析模型的精度与推理速度之间的关系', src: 'chart_2_accuracy_speed.png' },
  { name: '模型存储占用', description: '对比各模型的存储空间占用情况', src: 'chart_3_model_size.png' },
  { name: '性价比排名', description: '展示模型的性价比得分排名', src: 'chart_4_cost_performance.png' },
  { name: '模型类型分布', description: '统计分类模型和检测模型的数量分布', src: 'chart_5_model_type.png' },
  { name: '多维对比', description: '代表性模型的综合性能雷达图对比', src: 'chart_6_radar.png' },
  { name: '资源使用', description: '对比模型的参数量、GPU内存和模型大小', src: 'chart_7_resources.png' },
  { name: '损失对比', description: '对比模型的训练损失和验证损失', src: 'chart_8_loss.png' },
];

const distributionSpecies = [
  { id: 'spot-prawn', name: '牡丹虾', latinName: 'Pandalus platyceros', color: '#f44336',
    description: '冷水性虾类，因其鲜红的色泽而被誉为"牡丹虾"，有"虾王"的美誉。',
    distribution: '分布于日本海北部到白令海以及北美太平洋沿海地区。' },
  { id: 'prawn', name: '对虾', latinName: 'Penaeus spp.', color: '#4CAF50',
    description: '对虾科对虾属动物，广泛分布于全球温暖海域，是重要的经济虾类。',
    distribution: '广泛分布于全球温暖海域，包括中国沿海、东南亚、印度洋等地区。' },
  { id: 'mantis-shrimp', name: '皮皮虾', latinName: 'Oratosquilla oratoria', color: '#FF9800',
    description: '学名口虾蛄，俗称螳螂虾、虾爬子等，其实不是虾，而是口足目的成员。',
    distribution: '分布范围极广，俄罗斯、日本、中国、菲律宾、马来半岛等地均有分布。' },
  { id: 'boston-lobster', name: '波士顿龙虾', latinName: 'Homarus americanus', color: '#9C27B0',
    description: '即加拿大龙虾，生活于加拿大东海岸和美国东海岸海域，有一对大龙虾钳。',
    distribution: '加拿大东海岸和美国东海岸海域。' },
  { id: 'slipper-lobster', name: '琵琶虾', latinName: 'Scyllaridae spp.', color: '#795548',
    description: '又名蝉虾，体形扁平，呈琵琶状，分布于全球温暖海域。',
    distribution: '分布于全球温暖海域，包括太平洋、印度洋和大西洋。' },
  { id: 'tiger-prawn', name: '斑节虾', latinName: 'Penaeus monodon', color: '#FF5722',
    description: '斑节对虾是对虾属中个体最大的一种，最大个体可达350毫米。',
    distribution: '分布于中国沿海，日本南部、韩国、菲律宾、印尼、澳大利亚、泰国、印度至非洲东部沿岸均有分布。' },
  { id: 'blue-lobster', name: '法国蓝龙虾', latinName: 'Homarus gammarus', color: '#2196F3',
    description: '分布于法国布列塔尼附近的大西洋及英吉利海峡海域，亮蓝色外壳源于基因突变。',
    distribution: '法国布列塔尼附近的大西洋及英吉利海峡海域。' },
  { id: 'shrimp', name: '毛虾', latinName: 'Acetes spp.', color: '#607D8B',
    description: '小型经济虾类，干制品称虾皮，常成群栖息于河口区、港湾。',
    distribution: '中国毛虾仅分布在渤海、黄海海域中国和朝鲜近海以及东海、南海中国沿岸。' },
  { id: 'snapping-shrimp', name: '鼓虾', latinName: 'Alpheus spp.', color: '#E91E63',
    description: '遇敌时开闭大鳌之指，发出响声如小鼓，故称鼓虾。',
    distribution: '分布于中国、印度、西太平洋海域。' },
  { id: 'freshwater-shrimp', name: '河虾', latinName: 'Macrobrachium spp.', color: '#8BC34A',
    description: '淡水虾类，广泛分布于全球淡水系统，是重要的水产资源。',
    distribution: '广泛分布于全球淡水系统，包括河流、湖泊和溪流。' },
];

const shrimpSpecies = [
  {
    name: '对虾', scientific: 'Penaeus spp.',
    info: '对虾（Penaeus spp.）是重要的经济虾种之一，广泛分布于全球热带和亚热带海域。体型较大，肉质鲜美，是重要的水产养殖品种。',
    confidence: '92.7%', dataset: '50',
    image: 'https://pic.rmb.bdstatic.com/bjh/news/bf3f5a19e67cce812453938d76d94e44.png',
    size: '18-23cm', weight: '20-25g',
    distribution: '主要分布于太平洋、印度洋和大西洋的热带和亚热带海域，包括中国沿海、东南亚、澳大利亚北部等地区。',
    value: '对虾是全球最重要的水产养殖品种之一，年产量超过400万吨，占全球虾类养殖总量的70%以上。肉质鲜美，营养丰富，深受消费者喜爱。',
    habitat: '海水',
  },
  {
    name: '皮皮虾', scientific: 'Oratosquilla oratoria',
    info: '皮皮虾（Oratosquilla oratoria）又称螳螂虾，是一种具有攻击性的虾类。以其强大的前肢攻击力而闻名，能够击碎贝类外壳。',
    confidence: '89.3%', dataset: '50',
    image: 'https://copyright.bdstatic.com/vcg/creative/a9bd561433a86ae69dfd7f9ee7404a49.jpg@c_1,w_2048,h_1365,x_0,y_0',
    size: '15-18cm', weight: '30-50g',
    distribution: '主要分布于西太平洋海域，包括中国、日本、韩国沿海地区。常见于浅海沙泥底质区域。',
    value: '皮皮虾是重要的经济虾种，肉质鲜美，尤其在中国沿海地区广受欢迎。但其捕捞和养殖难度较大，市场价格较高。',
    habitat: '海水',
  },
  {
    name: '波士顿龙虾', scientific: 'Homarus americanus',
    info: '波士顿龙虾（Homarus americanus）又称美洲螯龙虾，是北美重要的经济虾种。体型较大，具有强大的螯足。',
    confidence: '94.1%', dataset: '50',
    image: 'https://img.yzcdn.cn/upload_files/2022/01/26/FjLmeSznMHjAabbmURBMrwC2Tgg2.jpg?imageView2/2/w/750/h/0/q/75/format/jpg',
    size: '20-60cm', weight: '0.5-4kg',
    distribution: '主要分布于北大西洋西部，从加拿大纽芬兰到美国北卡罗来纳州沿海地区。',
    value: '波士顿龙虾是全球最著名的龙虾品种之一，肉质鲜美，尤其螯足肉最为珍贵。是高档海鲜餐厅的常见食材。',
    habitat: '海水',
  },
  {
    name: '琵琶虾', scientific: 'Ibacus spp.',
    info: '琵琶虾（Ibacus spp.）因其扁平的身体和类似琵琶的形状而得名。主要分布于热带和亚热带海域。',
    confidence: '87.6%', dataset: '50',
    image: 'https://pic.rmb.bdstatic.com/bjh/99dfbd8cfa143059efce7529ea1aa8722238.jpeg@h_1280',
    size: '15-25cm', weight: '100-300g',
    distribution: '分布于印度洋-太平洋海域，包括澳大利亚、日本、中国南海等地区。常见于深海沙泥底质区域。',
    value: '琵琶虾肉质鲜美，口感独特，尤其在日本和澳大利亚市场广受欢迎。是高档海鲜料理的重要食材。',
    habitat: '海水',
  },
  {
    name: '斑节虾', scientific: 'Penaeus monodon',
    info: '斑节虾（Penaeus monodon）又称黑虎虾，是体型最大的对虾种类之一。以其明显的横带斑纹而得名。',
    confidence: '91.2%', dataset: '50',
    image: 'https://img1.baidu.com/it/u=1354867038,3279448993&fm=253&app=138&f=JPEG?w=500&h=666',
    size: '25-33cm', weight: '100-150g',
    distribution: '分布于印度洋至太平洋海域，包括东南亚、澳大利亚北部、东非和红海等地区。',
    value: '斑节虾是重要的经济虾种，肉质鲜美，体型大，市场价格高。但由于养殖难度较大，产量相对较低。',
    habitat: '海水',
  },
  {
    name: '牡丹虾', scientific: 'Pandalus borealis',
    info: '牡丹虾（Pandalus borealis）又称北极甜虾，以其鲜甜的口感和粉红色的虾肉而闻名。主要分布于寒冷海域。',
    confidence: '93.8%', dataset: '50',
    image: 'https://img01.yzcdn.cn/upload_files/2016/11/15/Fmoufrz2WSrkiEj75oCfVFybFXte.jpg!middle.jpg',
    size: '10-15cm', weight: '15-25g',
    distribution: '分布于北大西洋和北太平洋的寒冷海域，包括格陵兰、冰岛、挪威、加拿大和阿拉斯加等地。',
    value: '牡丹虾肉质鲜甜，口感细腻，尤其在日本市场被视为高档食材。常用于寿司和刺身料理。',
    habitat: '海水',
  },
  {
    name: '法国蓝龙虾', scientific: 'Homarus gammarus',
    info: '法国蓝龙虾（Homarus gammarus）又称欧洲螯龙虾，以其独特的蓝色外壳而闻名。是欧洲重要的经济虾种。',
    confidence: '95.2%', dataset: '50',
    image: 'https://b0.bdstatic.com/ugc/vYRfdyKC6OwOqRFlTVjZZA2e026eed27c7754b0484f1a72317a79d.jpg',
    size: '30-60cm', weight: '0.5-5kg',
    distribution: '主要分布于东大西洋海域，从挪威北部到摩洛哥沿海，包括地中海和黑海部分地区。',
    value: '法国蓝龙虾是高档海鲜的代表，肉质鲜美，尤其螯足肉最为珍贵。在欧洲市场享有盛誉，价格昂贵。',
    habitat: '海水',
  },
  {
    name: '毛虾', scientific: 'Acetes spp.',
    info: '毛虾（Acetes spp.）是小型虾类，主要分布于沿海浅水区域。体型小，呈半透明状，常用于加工制品。',
    confidence: '96.0%', dataset: '21',
    image: 'https://miaobi-lite.bj.bcebos.com/miaobi/5mao/b%2757qi5q%2Bb6Jm%2BXzE3MzM0NTE2NTAuMTc3MTk0OF8xNzMzNDUxNjUyLjk5MDEwNjY%3D%27/1.png',
    size: '3-5cm', weight: '0.5-1g',
    distribution: '广泛分布于印度洋-太平洋海域，包括中国沿海、东南亚、印度等地。常见于河口和浅海区域。',
    value: '毛虾是重要的经济虾种，主要用于制作虾酱、虾皮等加工产品。产量大，价格低廉，是重要的蛋白质来源。',
    habitat: '海水',
  },
  {
    name: '鼓虾', scientific: 'Alpheus spp.',
    info: '鼓虾（Alpheus spp.）又称手枪虾，以其能够发出响亮声音的大螯而闻名。主要生活在珊瑚礁和岩石缝隙中。',
    confidence: '88.7%', dataset: '25',
    image: 'https://p9.itc.cn/images01/20220717/0bbf9af10f1a4f6681a471b00924c3de.jpeg',
    size: '3-5cm', weight: '10-20g',
    distribution: '分布于全球热带和亚热带海域，常见于珊瑚礁、岩石缝隙和沙泥底质区域。',
    value: '鼓虾在生态系统中扮演重要角色，但其经济价值相对较低。主要用于水族馆观赏和科学研究。',
    habitat: '海水',
  },
  {
    name: '河虾', scientific: 'Macrobrachium spp.',
    info: '河虾（Macrobrachium spp.）是淡水虾类，广泛分布于全球河流、湖泊和溪流中。体型中等，肉质鲜美。',
    confidence: '91.8%', dataset: '50',
    image: 'https://inews.gtimg.com/news_bt/OvGvojbURXEo1yXKNdwGyp2PdJboxCiEE3ZyYfrwftbyQAA/641',
    size: '10-20cm', weight: '20-50g',
    distribution: '广泛分布于全球热带和亚热带地区的淡水环境，包括河流、湖泊、溪流和沼泽等。',
    value: '河虾是重要的淡水经济虾种，肉质鲜美，适合多种烹饪方式。在中国、东南亚等地广受欢迎。',
    habitat: '淡水',
  },
];
